INSERT INTO `emulator_settings` (`key`, `value`) VALUES
    ('login.access.jwt.ttl.seconds', '86400'),
    ('encryption.forced', 'false'),
    ('pet.stats.hunger_decay', '1'),
    ('pet.stats.thirst_decay', '1'),
    ('pet.stats.energy_decay', '1'),
    ('pet.stats.happiness_decay', '1'),
    ('pet.stats.energy_recovery', '5'),
    ('pet.stats.happiness_recovery', '1'),
    ('pet.threshold.hungry', '50'),
    ('pet.threshold.thirsty', '50'),
    ('pet.threshold.tired', '30'),
    ('pet.threshold.sad', '30'),
    ('pet.behavior.autonomous_action_delay', '5000'),
    ('pet.behavior.idle_wander_min_ms', '10000'),
    ('pet.behavior.idle_wander_max_ms', '30000'),
    ('pet.command.base_obey_chance', '70'),
    ('pet.command.cooldown_ms', '2000'),
    ('pet.command.max_same_spam', '3'),
    ('pet.command.min_energy', '15'),
    ('pet.command.min_happiness', '10'),
    ('pet.command.spam_reset_ms', '10000'),
    ('pet.breeding.timeout_seconds', '120'),
    ('hotel.url', 'http://localhost'),
    ('hotel.banzai.fill.threads', '2'),
    ('hotel.bot.butler.reachdistance', '3'),
    ('hotel.wired.bot.message.max_length', '100'),
    ('hotel.wired.show_message.max_length', '100'),
    ('hotel.wired.show_message.max_lines', '5'),
    ('login.probe.cache_enabled', 'true'),
    ('login.remember.days', '30'),
    ('motto.max_length', '38'),
    ('recycler.value', '8'),
    ('hotelview.promotinal.points', '120'),
    ('username', 'Habbo'),
    ('redeem.currency.trade', 'false'),
    ('translate.google.timeout.ms', '5000'),
    ('youtube.apikey', '')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

CREATE TABLE IF NOT EXISTS `housekeeping_log` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `timestamp` INT NOT NULL,
    `actor_id` INT NOT NULL,
    `actor_name` VARCHAR(64) NOT NULL DEFAULT '',
    `target_type` VARCHAR(16) NOT NULL DEFAULT 'user',
    `target_id` INT NOT NULL DEFAULT 0,
    `target_label` VARCHAR(128) NOT NULL DEFAULT '',
    `action` VARCHAR(64) NOT NULL DEFAULT '',
    `detail` VARCHAR(500) NOT NULL DEFAULT '',
    `success` TINYINT NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`),
    KEY `timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `emulator_texts` (`key`, `value`) VALUES
    ('commands.description.acc_modtool_room_info', ':emustats'),
    ('commands.description.cmd_add_youtube_playlist', ':add_youtube <base_item_id> <youtube_playlist_id>'),
    ('commands.description.cmd_give_prefix', ':giveprefix <username> <text> <color> [icon] [effect]'),
    ('commands.description.cmd_hidewired', ':hidewired'),
    ('commands.description.cmd_list_prefixes', ':listprefixes <username>'),
    ('commands.description.cmd_prefix_blacklist', ':prefixblacklist <add|remove|list> [word]'),
    ('commands.description.cmd_remove_prefix', ':removeprefix <username> <id|all>'),
    ('commands.description.cmd_setroom_template', ':setroom_template [yes]'),
    ('commands.description.cmd_softkick', ':softkick <username>'),
    ('commands.description.cmd_subscription', ':subscription <username> <type> <add|remove> [time]'),
    ('commands.description.cmd_update_youtube_playlists', ':update_youtube'),
    ('commands.error.cmd_badge.unknown_user', 'User not found.'),
    ('commands.error.cmd_dance.invalid_dance', 'Please use a valid number.'),
    ('commands.error.cmd_dance.outside_bounds', 'Please use a number between 0 and 4.'),
    ('commands.error.cmd_dance.usage', 'Usage: :dance <0-4>'),
    ('commands.error.cmd_empty', 'Could not empty inventory.'),
    ('commands.error.cmd_empty_bots', 'Could not empty bot inventory.'),
    ('commands.error.cmd_empty_pets', 'Could not empty pet inventory.'),
    ('commands.keys.cmd_softkick_error', '%user% not found.'),
    ('commands.keys.cmd_softkick_error_self', 'You cannot softkick yourself.'),
    ('commands.succes.cmd_diagonal.enabled', 'You can now walk diagonally.'),
    ('generic.days', 'days'),
    ('generic.pet.id', 'ID'),
    ('prereg.reward.you.received', 'You have received:'),
    ('scripter.warning.catalog.amount', 'User %username% tried to buy too many items: %itemname% on %pagename%.'),
    ('scripter.warning.chatlog', 'User %username% tried to request a chatlog without permission.'),
    ('scripter.warning.marketplace.negative', 'User %username% tried to sell %itemname% for negative credits (%credits%).')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);
